---
jenkins_1:
  name:     "jenkins_1"
  cpus:     2
  memory:   1024
  gui:      false
  box:      "ubuntu/xenial64"
  ip:       192.168.88.200

node_1:
  name:     "node_1"
  cpus:     2
  memory:   1024
  gui:      false
  box:      "ubuntu/xenial64"
  ip:       192.168.88.201
  
