---
- name: common software and configuration
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

- name: deploy jenkins
  hosts: jenkins
  become: yes
  become_method: sudo
  roles:
    - common
    - jenkins

